vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.wrap = false
vim.opt.swapfile = false
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.scrolloff = 8
vim.opt.signcolumn = "yes"
vim.opt.isfname:append("@-@")
vim.opt.virtualedit = "block"
vim.opt.termguicolors = true
vim.opt.updatetime = 50
vim.opt.tabstop = 4       -- Set tab width to 4 spaces
vim.opt.expandtab = false -- Use tabs instead of spaces
vim.opt.guicursor = "n-c-sm:block,i-ci-:ver25,r-cr-o:hor20,v-ve:hor75"
vim.g.netrw_banner = 0
